server:
  port: 8080

spring:
  application:
    name: food-delivery-backend

  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Vansh830
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:dGhpcyBpcyBhIGRldmVsb3BtZW50IG9ubHkgc2VjcmV0IGtleQ==}
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
